# Build Pipeline - Continuous Integration (Linux)
# Builds .NET Core 8 API + React TypeScript UI

stages:
- stage: Build
  displayName: 'Build and Test Application'
  
  variables:
    buildConfiguration: 'Release'
    dotnetVersion: '8.0.x'
    nodeVersion: '20.x'
    apiPath: 'SchoolManagement.API'
    uiPath: 'SchoolManagement.UI'
  
  jobs:
  ###########################################
  # Job 1: Build .NET Core 8 API
  ###########################################
  - job: BuildAPI
    displayName: 'Build .NET Core 8 API'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    # Install .NET Core SDK
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK $(dotnetVersion)'
      inputs:
        version: $(dotnetVersion)
        packageType: sdk
    
    # Display .NET version
    - bash: |
        dotnet --version
        dotnet --list-sdks
      displayName: 'Display .NET Version'
    
    # Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '$(apiPath)/**/*.csproj'
        feedsToUse: 'select'
    
    # Build API
    - task: DotNetCoreCLI@2
      displayName: 'Build API Project'
      inputs:
        command: 'build'
        projects: '$(apiPath)/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    
    # Run Unit Tests (if test project exists)
    - task: DotNetCoreCLI@2
      displayName: 'Run API Unit Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory $(Agent.TempDirectory)/TestResults'
        publishTestResults: false
      continueOnError: true
      condition: succeededOrFailed()
    
    # Publish Test Results
    - task: PublishTestResults@2
      displayName: 'Publish API Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: 'API Tests'
      condition: succeededOrFailed()
    
    # Publish Code Coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish API Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'
        failIfCoverageEmpty: false
      condition: succeededOrFailed()
    
    # Publish API
    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(apiPath)/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-restore'
        zipAfterPublish: true
        modifyOutputPath: false
    
    # List published files (Linux)
    - bash: |
        echo "Published API files:"
        ls -lah $(Build.ArtifactStagingDirectory)/api
      displayName: 'List Published API Files'
    
    # Publish API Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish API Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'api-drop'
        publishLocation: 'Container'
  
  ###########################################
  # Job 2: Build React TypeScript UI
  ###########################################
  - job: BuildUI
    displayName: 'Build React TypeScript UI'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    # Install Node.js
    - task: NodeTool@0
      displayName: 'Install Node.js $(nodeVersion)'
      inputs:
        versionSpec: $(nodeVersion)
    
    # Display Node and npm versions
    - bash: |
        node --version
        npm --version
      displayName: 'Display Node.js and npm versions'
    
    # Cache npm packages
    - task: Cache@2
      displayName: 'Cache npm packages'
      inputs:
        key: 'npm | "$(Agent.OS)" | $(uiPath)/package-lock.json'
        path: '$(uiPath)/node_modules'
        restoreKeys: |
          npm | "$(Agent.OS)"
        cacheHitVar: 'CACHE_RESTORED'
    
    # Install dependencies
    - bash: |
        cd $(Build.SourcesDirectory)/$(uiPath)
        echo "Installing dependencies..."
        npm ci --prefer-offline
      displayName: 'Install UI Dependencies'
    
    # Run ESLint
    - bash: |
        cd $(Build.SourcesDirectory)/$(uiPath)
        if grep -q '"lint"' package.json; then
          npm run lint
        else
          echo "##[warning]No lint script found - skipping"
        fi
      displayName: 'Run ESLint'
      continueOnError: true
    
    # Run TypeScript compiler check
    - bash: |
        cd $(Build.SourcesDirectory)/$(uiPath)
        npx tsc --noEmit
      displayName: 'TypeScript Type Check'
      continueOnError: true
    
    # Run UI Tests
    - bash: |
        cd $(Build.SourcesDirectory)/$(uiPath)
        
        # Check if test script exists
        if grep -q '"test"' package.json; then
          echo "Running tests..."
          npm test -- --coverage --watchAll=false --ci --reporters=default --reporters=jest-junit || true
        else
          echo "##[warning]No test script found in package.json - skipping tests"
        fi
      displayName: 'Run UI Tests'
      continueOnError: true
      condition: succeededOrFailed()
      env:
        CI: true
    
    # Publish UI Test Results
    - task: PublishTestResults@2
      displayName: 'Publish UI Test Results'
      inputs:
        testResultsFormat: 'xUnit'
        testResultsFiles: '$(Build.SourcesDirectory)/$(uiPath)/junit.xml'
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: 'UI Tests'
      continueOnError: true
      condition: succeededOrFailed()
    
    # Publish UI Code Coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish UI Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Build.SourcesDirectory)/$(uiPath)/coverage/cobertura-coverage.xml'
        reportDirectory: '$(Build.SourcesDirectory)/$(uiPath)/coverage'
        failIfCoverageEmpty: false
      continueOnError: true
      condition: succeededOrFailed()
    
    # Build React Application with error handling
    - bash: |
        cd $(Build.SourcesDirectory)/$(uiPath)
        echo "Current directory: $(pwd)"
        echo "================================"
        echo "Package.json build script:"
        cat package.json | grep -A 5 '"scripts"'
        echo "================================"
        echo "Running npm run build..."
        npm run build 2>&1 | tee build.log
        BUILD_EXIT_CODE=${PIPESTATUS[0]}
        echo "================================"
        echo "Build exit code: $BUILD_EXIT_CODE"
        
        if [ $BUILD_EXIT_CODE -ne 0 ]; then
          echo "##[error]Build failed with exit code $BUILD_EXIT_CODE"
          cat build.log
          exit $BUILD_EXIT_CODE
        fi
        
        echo "Checking for output folders..."
        if [ -d "build" ]; then
          echo "##vso[task.setvariable variable=buildOutputFolder]build"
          echo "✓ Found 'build' folder (Create React App)"
          ls -lah build/ | head -20
        elif [ -d "dist" ]; then
          echo "##vso[task.setvariable variable=buildOutputFolder]dist"
          echo "✓ Found 'dist' folder (Vite)"
          ls -lah dist/ | head -20
        else
          echo "##[error]No build output folder found!"
          echo "Directory contents:"
          ls -lah
          exit 1
        fi
      displayName: 'Build React UI'
      env:
        CI: false
        GENERATE_SOURCEMAP: false
        NODE_ENV: production
    
    # Copy build files
    - task: CopyFiles@2
      displayName: 'Copy UI Build Files'
      inputs:
        SourceFolder: '$(Build.SourcesDirectory)/$(uiPath)/$(buildOutputFolder)'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/ui'
        CleanTargetFolder: true
    
    # List build files
    - bash: |
        echo "UI Build files:"
        ls -lah $(Build.ArtifactStagingDirectory)/ui
      displayName: 'List UI Build Files'
    
    # Archive UI Build
    - task: ArchiveFiles@2
      displayName: 'Archive UI Build'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/ui'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/ui-build.zip'
        replaceExistingArchive: true
    
    # Publish UI Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish UI Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/ui-build.zip'
        ArtifactName: 'ui-drop'
        publishLocation: 'Container'
  
  ###########################################
  # Job 3: Build Summary
  ###########################################
  - job: BuildSummary
    displayName: 'Build Summary'
    dependsOn:
    - BuildAPI
    - BuildUI
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - bash: |
        echo "========================================"
        echo "Build Summary"
        echo "========================================"
        echo "Build Number: $(Build.BuildNumber)"
        echo "Source Branch: $(Build.SourceBranchName)"
        echo "Build Configuration: $(buildConfiguration)"
        echo "API Build: Completed"
        echo "UI Build: Completed"
        echo "========================================"
      displayName: 'Display Build Summary'
