# Dedicated Build Pipeline

trigger:
  branches:
    include:
    - main
    - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: school-app-variables

stages:
- stage: Build
  jobs:
  - job: BuildAndTest
    displayName: 'Build and Test Application'
    steps:
    
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'
    
    # Cache node modules for faster builds
    - task: Cache@2
      displayName: 'Cache npm packages'
      inputs:
        key: 'npm | "$(Agent.OS)" | package-lock.json'
        path: '$(System.DefaultWorkingDirectory)/node_modules'
        restoreKeys: |
          npm | "$(Agent.OS)"
    
    - script: |
        npm ci
      displayName: 'Install dependencies'
    
    - script: |
        npm run lint
      displayName: 'Run linter'
      continueOnError: true
    
    - script: |
        npm test -- --coverage --ci --reporters=default --reporters=jest-junit
      displayName: 'Run tests with coverage'
      env:
        NODE_ENV: test
    
    - task: PublishTestResults@2
      displayName: 'Publish test results'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/junit.xml'
        failTaskOnFailedTests: true
    
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish code coverage'
      condition: succeededOrFailed()
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
        reportDirectory: '$(System.DefaultWorkingDirectory)/coverage'
    
    - script: |
        npm run build
      displayName: 'Build application'
      env:
        NODE_ENV: production
    
    # Security scan
    - script: |
        npm audit --audit-level=moderate
      displayName: 'Security audit'
      continueOnError: true
    
    - task: CopyFiles@2
      displayName: 'Copy Files to Staging'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*
          !node_modules/**
          !coverage/**
          !tests/**
          !.git/**
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    
    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/school-app-$(Build.BuildId).zip'
        replaceExistingArchive: true
    
    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/school-app-$(Build.BuildId).zip'
        ArtifactName: 'drop'
        publishLocation: 'Container'