# Build Pipeline - Continuous Integration (Linux)
# Builds .NET Core 8 API + React TypeScript UI

stages:
- stage: Build
  displayName: 'Build and Test Application'
  
  variables:
    buildConfiguration: 'Release'
    dotnetVersion: '8.0.x'
    nodeVersion: '18.x'
    apiPath: 'SchoolManagement.API'
    uiPath: 'SchoolManagement.UI'
  
  jobs:
  ###########################################
  # Job 1: Build .NET Core 8 API
  ###########################################
  - job: BuildAPI
    displayName: 'Build .NET Core 8 API'
    pool:
      vmImage: 'ubuntu-latest'  # Changed to Linux
    
    steps:
    # Install .NET Core SDK
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK $(dotnetVersion)'
      inputs:
        version: $(dotnetVersion)
        packageType: sdk
    
    # Display .NET version
    - bash: |
        dotnet --version
        dotnet --list-sdks
      displayName: 'Display .NET Version'
    
    # Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '$(apiPath)/**/*.csproj'
        feedsToUse: 'select'
    
    # Build API
    - task: DotNetCoreCLI@2
      displayName: 'Build API Project'
      inputs:
        command: 'build'
        projects: '$(apiPath)/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    
    # Run Unit Tests (if test project exists)
    - task: DotNetCoreCLI@2
      displayName: 'Run API Unit Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory $(Agent.TempDirectory)/TestResults'
        publishTestResults: false
      continueOnError: true
      condition: succeededOrFailed()
    
    # Publish Test Results
    - task: PublishTestResults@2
      displayName: 'Publish API Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: 'API Tests'
      condition: succeededOrFailed()
    
    # Publish Code Coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish API Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'
        failIfCoverageEmpty: false
      condition: succeededOrFailed()
    
    # Publish API
    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(apiPath)/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-restore'
        zipAfterPublish: true
        modifyOutputPath: false
    
    # List published files (Linux)
    - bash: |
        echo "Published API files:"
        ls -lah $(Build.ArtifactStagingDirectory)/api
      displayName: 'List Published API Files'
    
    # Publish API Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish API Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'api-drop'
        publishLocation: 'Container'
  
  ###########################################
  # Job 2: Build React TypeScript UI
  ###########################################
  - job: BuildUI
    displayName: 'Build React TypeScript UI'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    # Install Node.js
    - task: NodeTool@0
      displayName: 'Install Node.js $(nodeVersion)'
      inputs:
        versionSpec: $(nodeVersion)
    
    # Display Node and npm versions
    - bash: |
        node --version
        npm --version
      displayName: 'Display Node.js and npm versions'
    
    # Cache npm packages
    - task: Cache@2
      displayName: 'Cache npm packages'
      inputs:
        key: 'npm | "$(Agent.OS)" | $(uiPath)/package-lock.json'
        path: '$(uiPath)/node_modules'
        restoreKeys: |
          npm | "$(Agent.OS)"
        cacheHitVar: 'CACHE_RESTORED'
    
    # Install dependencies
    - bash: |
        cd $(uiPath)
        npm ci
      displayName: 'Install UI Dependencies'
      condition: ne(variables.CACHE_RESTORED, 'true')
    
    # Run ESLint
    - bash: |
        cd $(uiPath)
        npm run lint
      displayName: 'Run ESLint'
      continueOnError: true
    
    # Run TypeScript compiler check
    - bash: |
        cd $(uiPath)
        npx tsc --noEmit
      displayName: 'TypeScript Type Check'
      continueOnError: true
    
    # Run UI Tests
    - bash: |
        cd $(uiPath)
        npm test -- --coverage --watchAll=false --ci --reporters=default --reporters=jest-junit
      displayName: 'Run UI Tests'
      continueOnError: true
      env:
        CI: true
    
    # Publish UI Test Results
    - task: PublishTestResults@2
      displayName: 'Publish UI Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(uiPath)/junit.xml'
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: 'UI Tests'
      condition: succeededOrFailed()
    
    # Publish UI Code Coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish UI Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(uiPath)/coverage/cobertura-coverage.xml'
        reportDirectory: '$(uiPath)/coverage'
        failIfCoverageEmpty: false
      condition: succeededOrFailed()
    
    # Build React Application
    - bash: |
        cd $(uiPath)
        npm run build
      displayName: 'Build React UI'
      env:
        CI: false
        GENERATE_SOURCEMAP: false
    
    # Copy build files
    - task: CopyFiles@2
      displayName: 'Copy UI Build Files'
      inputs:
        SourceFolder: '$(uiPath)/build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/ui'
        CleanTargetFolder: true
    
    # List build files
    - bash: |
        echo "UI Build files:"
        ls -lah $(Build.ArtifactStagingDirectory)/ui
      displayName: 'List UI Build Files'
    
    # Archive UI Build
    - task: ArchiveFiles@2
      displayName: 'Archive UI Build'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/ui'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/ui-build.zip'
        replaceExistingArchive: true
    
    # Publish UI Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish UI Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/ui-build.zip'
        ArtifactName: 'ui-drop'
        publishLocation: 'Container'
  
  ###########################################
  # Job 3: Build Summary
  ###########################################
  - job: BuildSummary
    displayName: 'Build Summary'
    dependsOn:
    - BuildAPI
    - BuildUI
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - bash: |
        echo "========================================"
        echo "Build Summary"
        echo "========================================"
        echo "Build Number: $(Build.BuildNumber)"
        echo "Source Branch: $(Build.SourceBranchName)"
        echo "Build Configuration: $(buildConfiguration)"
        echo "API Build: Completed"
        echo "UI Build: Completed"
        echo "========================================"
      displayName: 'Display Build Summary'# Build Pipeline - Continuous Integration (Linux)
# Builds .NET Core 8 API + React TypeScript UI

stages:
- stage: Build
  displayName: 'Build and Test Application'
  
  variables:
    buildConfiguration: 'Release'
    dotnetVersion: '8.0.x'
    nodeVersion: '18.x'
    apiPath: 'SchoolManagement.API'
    uiPath: 'SchoolManagement.UI'
  
  jobs:
  ###########################################
  # Job 1: Build .NET Core 8 API
  ###########################################
  - job: BuildAPI
    displayName: 'Build .NET Core 8 API'
    pool:
      vmImage: 'ubuntu-latest'  # Changed to Linux
    
    steps:
    # Install .NET Core SDK
    - task: UseDotNet@2
      displayName: 'Install .NET Core SDK $(dotnetVersion)'
      inputs:
        version: $(dotnetVersion)
        packageType: sdk
    
    # Display .NET version
    - bash: |
        dotnet --version
        dotnet --list-sdks
      displayName: 'Display .NET Version'
    
    # Restore NuGet packages
    - task: DotNetCoreCLI@2
      displayName: 'Restore NuGet Packages'
      inputs:
        command: 'restore'
        projects: '$(apiPath)/**/*.csproj'
        feedsToUse: 'select'
    
    # Build API
    - task: DotNetCoreCLI@2
      displayName: 'Build API Project'
      inputs:
        command: 'build'
        projects: '$(apiPath)/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-restore'
    
    # Run Unit Tests (if test project exists)
    - task: DotNetCoreCLI@2
      displayName: 'Run API Unit Tests'
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --logger trx --results-directory $(Agent.TempDirectory)/TestResults'
        publishTestResults: false
      continueOnError: true
      condition: succeededOrFailed()
    
    # Publish Test Results
    - task: PublishTestResults@2
      displayName: 'Publish API Test Results'
      inputs:
        testResultsFormat: 'VSTest'
        testResultsFiles: '$(Agent.TempDirectory)/TestResults/**/*.trx'
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: 'API Tests'
      condition: succeededOrFailed()
    
    # Publish Code Coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish API Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(Agent.TempDirectory)/TestResults/**/coverage.cobertura.xml'
        failIfCoverageEmpty: false
      condition: succeededOrFailed()
    
    # Publish API
    - task: DotNetCoreCLI@2
      displayName: 'Publish API'
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '$(apiPath)/**/*.csproj'
        arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)/api --no-restore'
        zipAfterPublish: true
        modifyOutputPath: false
    
    # List published files (Linux)
    - bash: |
        echo "Published API files:"
        ls -lah $(Build.ArtifactStagingDirectory)/api
      displayName: 'List Published API Files'
    
    # Publish API Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish API Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/api'
        ArtifactName: 'api-drop'
        publishLocation: 'Container'
  
  ###########################################
  # Job 2: Build React TypeScript UI
  ###########################################
  - job: BuildUI
    displayName: 'Build React TypeScript UI'
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    # Install Node.js
    - task: NodeTool@0
      displayName: 'Install Node.js $(nodeVersion)'
      inputs:
        versionSpec: $(nodeVersion)
    
    # Display Node and npm versions
    - bash: |
        node --version
        npm --version
      displayName: 'Display Node.js and npm versions'
    
    # Cache npm packages
    - task: Cache@2
      displayName: 'Cache npm packages'
      inputs:
        key: 'npm | "$(Agent.OS)" | $(uiPath)/package-lock.json'
        path: '$(uiPath)/node_modules'
        restoreKeys: |
          npm | "$(Agent.OS)"
        cacheHitVar: 'CACHE_RESTORED'
    
    # Install dependencies
    - bash: |
        cd $(uiPath)
        npm ci
      displayName: 'Install UI Dependencies'
      condition: ne(variables.CACHE_RESTORED, 'true')
    
    # Run ESLint
    - bash: |
        cd $(uiPath)
        npm run lint
      displayName: 'Run ESLint'
      continueOnError: true
    
    # Run TypeScript compiler check
    - bash: |
        cd $(uiPath)
        npx tsc --noEmit
      displayName: 'TypeScript Type Check'
      continueOnError: true
    
    # Run UI Tests
    - bash: |
        cd $(uiPath)
        npm test -- --coverage --watchAll=false --ci --reporters=default --reporters=jest-junit
      displayName: 'Run UI Tests'
      continueOnError: true
      env:
        CI: true
    
    # Publish UI Test Results
    - task: PublishTestResults@2
      displayName: 'Publish UI Test Results'
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '$(uiPath)/junit.xml'
        mergeTestResults: true
        failTaskOnFailedTests: false
        testRunTitle: 'UI Tests'
      condition: succeededOrFailed()
    
    # Publish UI Code Coverage
    - task: PublishCodeCoverageResults@2
      displayName: 'Publish UI Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(uiPath)/coverage/cobertura-coverage.xml'
        reportDirectory: '$(uiPath)/coverage'
        failIfCoverageEmpty: false
      condition: succeededOrFailed()
    
    # Build React Application
    - bash: |
        cd $(uiPath)
        npm run build
      displayName: 'Build React UI'
      env:
        CI: false
        GENERATE_SOURCEMAP: false
    
    # Copy build files
    - task: CopyFiles@2
      displayName: 'Copy UI Build Files'
      inputs:
        SourceFolder: '$(uiPath)/build'
        Contents: '**'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/ui'
        CleanTargetFolder: true
    
    # List build files
    - bash: |
        echo "UI Build files:"
        ls -lah $(Build.ArtifactStagingDirectory)/ui
      displayName: 'List UI Build Files'
    
    # Archive UI Build
    - task: ArchiveFiles@2
      displayName: 'Archive UI Build'
      inputs:
        rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/ui'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/ui-build.zip'
        replaceExistingArchive: true
    
    # Publish UI Artifacts
    - task: PublishBuildArtifacts@1
      displayName: 'Publish UI Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)/ui-build.zip'
        ArtifactName: 'ui-drop'
        publishLocation: 'Container'
  
  ###########################################
  # Job 3: Build Summary
  ###########################################
  - job: BuildSummary
    displayName: 'Build Summary'
    dependsOn:
    - BuildAPI
    - BuildUI
    pool:
      vmImage: 'ubuntu-latest'
    
    steps:
    - bash: |
        echo "========================================"
        echo "Build Summary"
        echo "========================================"
        echo "Build Number: $(Build.BuildNumber)"
        echo "Source Branch: $(Build.SourceBranchName)"
        echo "Build Configuration: $(buildConfiguration)"
        echo "API Build: Completed"
        echo "UI Build: Completed"
        echo "========================================"
      displayName: 'Display Build Summary'