# Multi-Stage Release Pipeline

trigger: none # Triggered by build completion

resources:
  pipelines:
  - pipeline: buildPipeline
    source: 'SchoolManagementApp-CI'
    trigger:
      branches:
        include:
        - main
        - develop

variables:
  - group: school-app-variables

stages:
- stage: DeployDevelopment
  displayName: 'Deploy to Development'
  condition: eq(variables['resources.pipeline.buildPipeline.sourceBranch'], 'refs/heads/develop')
  jobs:
  - deployment: DeployDev
    displayName: 'Deploy Dev Environment'
    environment: 'development'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: none
          
          - download: buildPipeline
            artifact: drop
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Dev App Service'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              WebAppName: '$(DEV_WEBAPP_NAME)'
              packageForLinux: '$(Pipeline.Workspace)/buildPipeline/drop/*.zip'
              RuntimeStack: 'NODE|18-lts'
              StartupCommand: 'npm run start:prod'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configure App Settings'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(DEV_WEBAPP_NAME)'
              resourceGroupName: '$(DEV_RESOURCE_GROUP)'
              appSettings: |
                [
                  {
                    "name": "NODE_ENV",
                    "value": "development",
                    "slotSetting": false
                  },
                  {
                    "name": "DATABASE_URL",
                    "value": "postgresql://pgadmin:$(DEV_DATABASE_PASSWORD)@$(DEV_DATABASE_SERVER).postgres.database.azure.com:5432/schooldb?ssl=true",
                    "slotSetting": false
                  },
                  {
                    "name": "SESSION_SECRET",
                    "value": "$(SESSION_SECRET)",
                    "slotSetting": false
                  },
                  {
                    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
                    "value": "$(DEV_APPINSIGHTS_CONNECTION_STRING)",
                    "slotSetting": false
                  }
                ]
          
          - task: AzureCLI@2
            displayName: 'Run Database Migrations'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running database migrations..."
                # Install postgresql client
                sudo apt-get update
                sudo apt-get install -y postgresql-client
                
                # Run migrations
                export PGPASSWORD='$(DEV_DATABASE_PASSWORD)'
                psql -h $(DEV_DATABASE_SERVER).postgres.database.azure.com \
                     -U pgadmin \
                     -d schooldb \
                     -f $(Pipeline.Workspace)/buildPipeline/drop/database/migrations/*.sql
          
          - task: AzureCLI@2
            displayName: 'Verify Deployment'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Verifying deployment..."
                max_attempts=10
                attempt=1
                
                while [ $attempt -le $max_attempts ]; do
                  response=$(curl -s -o /dev/null -w "%{http_code}" https://$(DEV_WEBAPP_NAME).azurewebsites.net/health)
                  
                  if [ $response -eq 200 ]; then
                    echo "✅ Deployment verified successfully!"
                    exit 0
                  fi
                  
                  echo "Attempt $attempt/$max_attempts: Status code $response. Waiting..."
                  sleep 10
                  attempt=$((attempt + 1))
                done
                
                echo "❌ Deployment verification failed!"
                exit 1

- stage: DeployProduction
  displayName: 'Deploy to Production'
  dependsOn: []
  condition: eq(variables['resources.pipeline.buildPipeline.sourceBranch'], 'refs/heads/main')
  jobs:
  - deployment: DeployProd
    displayName: 'Deploy Production Environment'
    environment: 'production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        preDeploy:
          steps:
          - task: AzureCLI@2
            displayName: 'Pre-Deployment: Backup Database'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Creating database backup..."
                DATE=$(date +%Y%m%d_%H%M%S)
                BACKUP_FILE="prod_backup_$DATE.sql"
                
                # Install postgresql client
                sudo apt-get update
                sudo apt-get install -y postgresql-client
                
                # Create backup
                export PGPASSWORD='$(PROD_DATABASE_PASSWORD)'
                pg_dump -h $(PROD_DATABASE_SERVER).postgres.database.azure.com \
                        -U pgadmin \
                        -d schooldb \
                        --clean \
                        --if-exists > $BACKUP_FILE
                
                # Upload to Azure Storage
                az storage blob upload \
                  --account-name $(PROD_STORAGE_ACCOUNT) \
                  --container-name backups \
                  --name $BACKUP_FILE \
                  --file $BACKUP_FILE \
                  --auth-mode login
                
                echo "✅ Backup completed: $BACKUP_FILE"
          
          - task: AzureCLI@2
            displayName: 'Pre-Deployment: Health Check'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Checking current application health..."
                response=$(curl -s https://$(PROD_WEBAPP_NAME).azurewebsites.net/health)
                echo "Current health status: $response"
        
        deploy:
          steps:
          - checkout: none
          
          - download: buildPipeline
            artifact: drop
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy to Production App Service'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              WebAppName: '$(PROD_WEBAPP_NAME)'
              packageForLinux: '$(Pipeline.Workspace)/buildPipeline/drop/*.zip'
              RuntimeStack: 'NODE|18-lts'
              StartupCommand: 'npm run start:prod'
              # Enable deployment slots for zero-downtime (requires Standard tier)
              # deployToSlotOrASE: true
              # slotName: 'staging'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configure Production Settings'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(PROD_WEBAPP_NAME)'
              resourceGroupName: '$(PROD_RESOURCE_GROUP)'
              appSettings: |
                [
                  {
                    "name": "NODE_ENV",
                    "value": "production",
                    "slotSetting": false
                  },
                  {
                    "name": "DATABASE_URL",
                    "value": "postgresql://pgadmin:$(PROD_DATABASE_PASSWORD)@$(PROD_DATABASE_SERVER).postgres.database.azure.com:5432/schooldb?ssl=true",
                    "slotSetting": false
                  },
                  {
                    "name": "SESSION_SECRET",
                    "value": "$(SESSION_SECRET)",
                    "slotSetting": false
                  },
                  {
                    "name": "JWT_SECRET",
                    "value": "$(JWT_SECRET)",
                    "slotSetting": false
                  },
                  {
                    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
                    "value": "$(PROD_APPINSIGHTS_CONNECTION_STRING)",
                    "slotSetting": false
                  },
                  {
                    "name": "STORAGE_CONNECTION_STRING",
                    "value": "$(PROD_STORAGE_CONNECTION_STRING)",
                    "slotSetting": false
                  }
                ]
          
          - task: AzureCLI@2
            displayName: 'Run Production Migrations'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running production database migrations..."
                sudo apt-get update
                sudo apt-get install -y postgresql-client
                
                export PGPASSWORD='$(PROD_DATABASE_PASSWORD)'
                psql -h $(PROD_DATABASE_SERVER).postgres.database.azure.com \
                     -U pgadmin \
                     -d schooldb \
                     -f $(Pipeline.Workspace)/buildPipeline/drop/database/migrations/*.sql
        
        routeTraffic:
          steps:
          - task: AzureCLI@2
            displayName: 'Smoke Tests'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                echo "Running smoke tests..."
                
                # Test health endpoint
                health_response=$(curl -s -o /dev/null -w "%{http_code}" https://$(PROD_WEBAPP_NAME).azurewebsites.net/health)
                echo "Health check: $health_response"
                
                # Test API endpoint
                api_response=$(curl -s -o /dev/null -w "%{http_code}" https://$(PROD_WEBAPP_NAME).azurewebsites.net/api/status)
                echo "API check: $api_response"
                
                if [ $health_response -eq 200 ] && [ $api_response -eq 200 ]; then
                  echo "✅ All smoke tests passed!"
                  exit 0
                else
                  echo "❌ Smoke tests failed!"
                  exit 1
                fi
        
        on:
          failure:
            steps:
            - task: AzureCLI@2
              displayName: 'Rollback on Failure'
              inputs:
                azureSubscription: '$(AZURE_SUBSCRIPTION)'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "⚠️ Deployment failed! Initiating rollback..."
                  
                  # Get previous deployment
                  # az webapp deployment list --name $(PROD_WEBAPP_NAME) --resource-group $(PROD_RESOURCE_GROUP)
                  
                  # Send alert
                  echo "Sending alert to operations team..."
          
          success:
            steps:
            - task: AzureCLI@2
              displayName: 'Post-Deployment Validation'
              inputs:
                azureSubscription: '$(AZURE_SUBSCRIPTION)'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  echo "✅ Deployment successful!"
                  echo "Application URL: https://$(PROD_WEBAPP_NAME).azurewebsites.net"
                  
                  # Clean up old backups (keep last 10)
                  az storage blob list \
                    --account-name $(PROD_STORAGE_ACCOUNT) \
                    --container-name backups \
                    --prefix prod_backup_ \
                    --query "sort_by([].{name:name, lastModified:properties.lastModified}, &lastModified)[:-10].name" \
                    --output tsv | \
                  xargs -I {} az storage blob delete \
                    --account-name $(PROD_STORAGE_ACCOUNT) \
                    --container-name backups \
                    --name {}
# ```

# ## Phase 7: Environment Configuration

# ### 7.1 Create Environments in Azure DevOps

# 1. Go to Pipelines → Environments
# 2. Click "New environment"

# **Development Environment:**
# ```
# Name: development
# Description: Development environment for testing
# Resource: None (for now)
# ```

# **Production Environment:**
# ```
# Name: production
# Description: Production environment with approvals
# Resource: None
# ```

# ### 7.2 Add Approval Gates (Production)

# 1. Click on "production" environment
# 2. Click the "..." menu → "Approvals and checks"
# 3. Click "+" → "Approvals"

# **Configuration:**
# ```
# Approvers: [Your email or team]
# Instructions: "Review deployment changes before approving"
# Timeout: 30 days
# Minimum number of approvers: 1
# Allow approvers to approve their own runs: No
# ```

# 4. Add "Business hours" check (optional):
# ```
# Start time: 09:00
# End time: 18:00
# Time zone: Your timezone
# Days: Monday - Friday