# Release Pipeline - Continuous Deployment (Linux)
# Deploys .NET Core 8 API + React TypeScript UI to Azure

parameters:
- name: environment
  type: string
  default: 'development'
  values:
  - development
  - production

- name: dependsOn
  type: string
  default: 'Build'

- name: condition
  type: string
  default: 'succeeded()'

# Root-level variables - accessible to all stages/jobs
variables:
- name: AZURE_SUBSCRIPTION
  value: 'Azure-School-Management'  # Your service connection name

# Optionally link variable groups (recommended)
# - group: Development-Variables
# - group: Production-Variables

stages:
- stage: Deploy_${{ parameters.environment }}
  displayName: 'Deploy to ${{ parameters.environment }}'
  dependsOn: ${{ parameters.dependsOn }}
  condition: ${{ parameters.condition }}
  
  variables:
    # Environment-specific variables
    ${{ if eq(parameters.environment, 'development') }}:
      apiWebAppName: $(DEV_API_WEBAPP_NAME)
      uiWebAppName: $(DEV_UI_WEBAPP_NAME)
      resourceGroup: $(DEV_RESOURCE_GROUP)
      databaseServer: $(DEV_DATABASE_SERVER)
      dbUsername: $(DEV_DB_USERNAME)
      dbPassword: $(DEV_DB_PASSWORD)
      appInsightsConnectionString: $(DEV_APPINSIGHTS_CONNECTION_STRING)
      storageAccount: $(DEV_STORAGE_ACCOUNT)
      aspnetEnvironment: 'Development'
    
    ${{ if eq(parameters.environment, 'production') }}:
      apiWebAppName: $(PROD_API_WEBAPP_NAME)
      uiWebAppName: $(PROD_UI_WEBAPP_NAME)
      resourceGroup: $(PROD_RESOURCE_GROUP)
      databaseServer: $(PROD_DATABASE_SERVER)
      dbUsername: $(PROD_DB_USERNAME)
      dbPassword: $(PROD_DB_PASSWORD)
      appInsightsConnectionString: $(PROD_APPINSIGHTS_CONNECTION_STRING)
      storageAccount: $(PROD_STORAGE_ACCOUNT)
      storageKey: $(PROD_STORAGE_KEY)
      aspnetEnvironment: 'Production'
  
  jobs:
  ###########################################
  # Job 1: Deploy API
  ###########################################
  - deployment: DeployAPI
    displayName: 'Deploy API to ${{ parameters.environment }}'
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'ubuntu-latest'
    
    strategy:
      runOnce:
        preDeploy:
          steps:
          - bash: |
              echo "========================================"
              echo "Pre-Deployment Checklist"
              echo "========================================"
              echo "Environment: ${{ parameters.environment }}"
              echo "API Web App: $(apiWebAppName)"
              echo "Resource Group: $(resourceGroup)"
              echo "Database Server: $(databaseServer)"
              echo "Azure Subscription: $(AZURE_SUBSCRIPTION)"
              echo "========================================"
            displayName: 'Pre-Deployment Checklist'
          
          # Backup Database (Production Only)
          - ${{ if eq(parameters.environment, 'production') }}:
            - task: AzureCLI@2
              displayName: 'Backup Production Database'
              inputs:
                azureSubscription: '$(AZURE_SUBSCRIPTION)'
                scriptType: 'bash'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  DATE=$(date +%Y%m%d_%H%M%S)
                  BACKUP_NAME="api_backup_$DATE"
                  
                  echo "Creating database backup: $BACKUP_NAME"
                  
                  az sql db export \
                    --resource-group $(resourceGroup) \
                    --server $(databaseServer) \
                    --name SchoolDB \
                    --admin-user $(dbUsername) \
                    --admin-password $(dbPassword) \
                    --storage-key-type StorageAccessKey \
                    --storage-key $(storageKey) \
                    --storage-uri "https://$(storageAccount).blob.core.windows.net/backups/$BACKUP_NAME.bacpac" \
                  && echo "✅ Backup completed: $BACKUP_NAME" \
                  || echo "⚠️ Backup failed, but continuing deployment..."
        
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download API Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'api-drop'
              downloadPath: '$(Pipeline.Workspace)'
          
          - bash: |
              echo "Downloaded files:"
              ls -lah $(Pipeline.Workspace)/api-drop
            displayName: 'List Downloaded Files'
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy API to Azure App Service'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              WebAppName: '$(apiWebAppName)'
              packageForLinux: '$(Pipeline.Workspace)/api-drop/**/*.zip'
              RuntimeStack: 'DOTNETCORE|8.0'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configure API App Settings'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(apiWebAppName)'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "ASPNETCORE_ENVIRONMENT",
                    "value": "$(aspnetEnvironment)",
                    "slotSetting": false
                  },
                  {
                    "name": "ConnectionStrings__DefaultConnection",
                    "value": "Server=$(databaseServer).database.windows.net;Database=SchoolDB;User Id=$(dbUsername);Password=$(dbPassword);",
                    "slotSetting": false
                  },
                  {
                    "name": "APPLICATIONINSIGHTS_CONNECTION_STRING",
                    "value": "$(appInsightsConnectionString)",
                    "slotSetting": false
                  },
                  {
                    "name": "AllowedOrigins",
                    "value": "https://$(uiWebAppName).azurewebsites.net",
                    "slotSetting": false
                  }
                ]
          
          - bash: |
              echo "Waiting 30 seconds for API to start..."
              sleep 30
            displayName: 'Wait for API to Start'
        
        routeTraffic:
          steps:
          - bash: |
              MAX_ATTEMPTS=10
              ATTEMPT=1
              API_URL="https://$(apiWebAppName).azurewebsites.net/health"
              
              echo "Testing API Health at: $API_URL"
              
              while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
                  echo "Attempt $ATTEMPT/$MAX_ATTEMPTS..."
                  
                  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $API_URL)
                  
                  if [ $HTTP_CODE -eq 200 ]; then
                      echo "✅ API Health Check Passed!"
                      RESPONSE=$(curl -s $API_URL)
                      echo "Response: $RESPONSE"
                      exit 0
                  fi
                  
                  echo "⚠️ Attempt $ATTEMPT failed with status code: $HTTP_CODE"
                  
                  if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
                      echo "Waiting 10 seconds before retry..."
                      sleep 10
                  fi
                  
                  ATTEMPT=$((ATTEMPT + 1))
              done
              
              echo "❌ API Health Check Failed after $MAX_ATTEMPTS attempts!"
              exit 1
            displayName: 'API Health Check'
          
          - ${{ if eq(parameters.environment, 'production') }}:
            - bash: |
                API_URL="https://$(apiWebAppName).azurewebsites.net"
                
                echo "Testing API endpoints..."
                
                SWAGGER_CODE=$(curl -s -o /dev/null -w "%{http_code}" "$API_URL/swagger")
                
                if [ $SWAGGER_CODE -eq 200 ]; then
                    echo "✅ Swagger endpoint accessible"
                else
                    echo "⚠️ Swagger endpoint not accessible (Status: $SWAGGER_CODE)"
                    echo "   This might be expected in production"
                fi
                
                echo "✅ API smoke tests completed"
              displayName: 'Test API Endpoints'
        
        on:
          failure:
            steps:
            - bash: |
                echo "========================================"
                echo "⚠️ API DEPLOYMENT FAILED!"
                echo "========================================"
                echo "Environment: ${{ parameters.environment }}"
                echo "Pipeline: $(Build.DefinitionName)"
                echo "Build: $(Build.BuildNumber)"
                echo "API Web App: $(apiWebAppName)"
                echo "========================================"
              displayName: 'Deployment Failed - Send Alert'
          
          success:
            steps:
            - bash: |
                echo "========================================"
                echo "✅ API DEPLOYMENT SUCCESSFUL!"
                echo "========================================"
                echo "Environment: ${{ parameters.environment }}"
                echo "API URL: https://$(apiWebAppName).azurewebsites.net"
                echo "Health: https://$(apiWebAppName).azurewebsites.net/health"
                echo "========================================"
              displayName: 'Deployment Successful'
  
  ###########################################
  # Job 2: Deploy UI
  ###########################################
  - deployment: DeployUI
    displayName: 'Deploy UI to ${{ parameters.environment }}'
    dependsOn: DeployAPI
    condition: succeeded()
    environment: ${{ parameters.environment }}
    pool:
      vmImage: 'ubuntu-latest'
    
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download UI Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'ui-drop'
              downloadPath: '$(Pipeline.Workspace)'
          
          - task: ExtractFiles@1
            displayName: 'Extract UI Build'
            inputs:
              archiveFilePatterns: '$(Pipeline.Workspace)/ui-drop/ui-build.zip'
              destinationFolder: '$(Pipeline.Workspace)/ui-extracted'
              cleanDestinationFolder: true
          
          - bash: |
              cat > $(Pipeline.Workspace)/ui-extracted/web.config << 'EOF'
              <?xml version="1.0" encoding="utf-8"?>
              <configuration>
                <system.webServer>
                  <rewrite>
                    <rules>
                      <rule name="React Routes" stopProcessing="true">
                        <match url=".*" />
                        <conditions logicalGrouping="MatchAll">
                          <add input="{REQUEST_FILENAME}" matchType="IsFile" negate="true" />
                          <add input="{REQUEST_FILENAME}" matchType="IsDirectory" negate="true" />
                          <add input="{REQUEST_URI}" pattern="^/(api)" negate="true" />
                        </conditions>
                        <action type="Rewrite" url="/" />
                      </rule>
                    </rules>
                  </rewrite>
                  <staticContent>
                    <mimeMap fileExtension=".json" mimeType="application/json" />
                  </staticContent>
                </system.webServer>
              </configuration>
              EOF
              
              echo "✅ web.config created for SPA routing"
            displayName: 'Create web.config'
          
          - bash: |
              echo "Extracted UI files:"
              ls -lah $(Pipeline.Workspace)/ui-extracted
            displayName: 'List Extracted Files'
          
          - task: AzureRmWebAppDeployment@4
            displayName: 'Deploy UI to Azure App Service'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appType: 'webAppLinux'
              WebAppName: '$(uiWebAppName)'
              packageForLinux: '$(Pipeline.Workspace)/ui-extracted'
              RuntimeStack: 'NODE|18-lts'
          
          - task: AzureAppServiceSettings@1
            displayName: 'Configure UI App Settings'
            inputs:
              azureSubscription: '$(AZURE_SUBSCRIPTION)'
              appName: '$(uiWebAppName)'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "REACT_APP_API_URL",
                    "value": "https://$(apiWebAppName).azurewebsites.net",
                    "slotSetting": false
                  },
                  {
                    "name": "WEBSITE_NODE_DEFAULT_VERSION",
                    "value": "~18",
                    "slotSetting": false
                  },
                  {
                    "name": "SCM_DO_BUILD_DURING_DEPLOYMENT",
                    "value": "false",
                    "slotSetting": false
                  }
                ]
          
          - bash: |
              echo "Waiting 20 seconds for UI to start..."
              sleep 20
            displayName: 'Wait for UI to Start'
        
        routeTraffic:
          steps:
          - bash: |
              MAX_ATTEMPTS=10
              ATTEMPT=1
              UI_URL="https://$(uiWebAppName).azurewebsites.net"
              
              echo "Testing UI at: $UI_URL"
              
              while [ $ATTEMPT -le $MAX_ATTEMPTS ]; do
                  echo "Attempt $ATTEMPT/$MAX_ATTEMPTS..."
                  
                  HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" $UI_URL)
                  
                  if [ $HTTP_CODE -eq 200 ]; then
                      echo "✅ UI is accessible! Status code: $HTTP_CODE"
                      exit 0
                  fi
                  
                  echo "⚠️ Attempt $ATTEMPT failed with status code: $HTTP_CODE"
                  
                  if [ $ATTEMPT -lt $MAX_ATTEMPTS ]; then
                      echo "Waiting 10 seconds before retry..."
                      sleep 10
                  fi
                  
                  ATTEMPT=$((ATTEMPT + 1))
              done
              
              echo "❌ UI Smoke Test Failed after $MAX_ATTEMPTS attempts!"
              exit 1
            displayName: 'UI Smoke Test'
        
        on:
          success:
            steps:
            - bash: |
                echo "========================================"
                echo "✅ FULL DEPLOYMENT SUCCESSFUL!"
                echo "========================================"
                echo "Environment: ${{ parameters.environment }}"
                echo ""
                echo "API URL: https://$(apiWebAppName).azurewebsites.net"
                echo "UI URL: https://$(uiWebAppName).azurewebsites.net"
                echo ""
                echo "API Health: https://$(apiWebAppName).azurewebsites.net/health"
                echo "API Swagger: https://$(apiWebAppName).azurewebsites.net/swagger"
                echo "========================================"
              displayName: 'Deployment Complete'
