// import {
//   Users,
//   Calendar,
//   BookOpen,
//   DollarSign,
//   UserCheck,
//   Bell,
//   Settings,
//   BarChart3,
//   GraduationCap,
//   CreditCard,
//   Shield,
//   Clock,
//   Upload,
//   LayoutGrid,
//   Wand2,
//   Building,
//   UserPlus,
//   Key,
//   Menu,
//   ArrowUpCircle,
//   FileText,
//   MessageSquare,
//   ClipboardList,
//   Home,
//   CheckCircle,
//   Bus,
//   Route,
//   MapPin,
//   Building2,
//   Utensils,
//   UserCheck2,
// } from "lucide-react";
// import { UserRole } from "@/contexts/AuthContext";
// import { LucideIcon } from "lucide-react";

// export interface NavItem {
//   title: string;
//   url: string;
//   icon: LucideIcon;
//   roles: UserRole[];
//   children?: NavItem[];
//   badge?: string | number;
//   description?: string;
// }

// export const NAVIGATION_CONFIG: NavItem[] = [
//   {
//     title: "Dashboard",
//     url: "/dashboard",
//     icon: BarChart3,
//     roles: ["Admin", "Teacher", "Student", "HR", "Accountant"],
//     description: "Overview and analytics",
//   },
//   {
//     title: "Class Management",
//     url: "/classes",
//     icon: BookOpen,
//     roles: ["Admin", "Teacher"],
//     description: "Manage classes and schedules",
//     children: [
//       {
//         title: "All Classes",
//         url: "/classes",
//         icon: BookOpen,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Timetable Builder",
//         url: "/classes/timetable-builder",
//         icon: LayoutGrid,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Auto Scheduler",
//         url: "/classes/auto-scheduler",
//         icon: Wand2,
//         roles: ["Admin"],
//       },
//       {
//         title: "Room Allocation",
//         url: "/classes/room-allocation",
//         icon: Building,
//         roles: ["Admin"],
//       },
//       {
//         title: "Import/Export",
//         url: "/classes/import-export",
//         icon: Upload,
//         roles: ["Admin"],
//       },
//       {
//         title: "Teacher Workload",
//         url: "/classes/teacher-workload",
//         icon: Clock,
//         roles: ["Admin"],
//       },
//     ],
//   },
//   {
//     title: "Students",
//     url: "/students",
//     icon: GraduationCap,
//     roles: ["Admin", "Teacher"],
//     description: "Student management",
//     children: [
//       {
//         title: "All Students",
//         url: "/students",
//         icon: Users,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Add Student",
//         url: "/students/add",
//         icon: UserPlus,
//         roles: ["Admin"],
//       },
//       {
//         title: "Promotion",
//         url: "/students/promotion",
//         icon: ArrowUpCircle,
//         roles: ["Admin"],
//       },
//       {
//         title: "Report Cards",
//         url: "/students/report-cards/templates",
//         icon: FileText,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Generate Report Cards",
//         url: "/students/report-cards/generate",
//         icon: FileText,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Assignments",
//         url: "/students/assignments",
//         icon: BookOpen,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Progress Reports",
//         url: "/students/progress",
//         icon: BarChart3,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Academic Calendar",
//         url: "/calendar",
//         icon: Calendar,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//       {
//         title: "Admit Card",
//         url: "/admit-card",
//         icon: CreditCard,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//     ],
//   },
//   {
//     title: "Assignments",
//     url: "/assignments/manage",
//     icon: ClipboardList,
//     roles: ["Admin", "Teacher"],
//     description: "Manage assignments",
//   },
//   {
//     title: "Leave Approval",
//     url: "/leave/approval",
//     icon: CheckCircle,
//     roles: ["Admin", "Teacher"],
//     description: "Approve leave requests",
//   },
//   {
//     title: "Attendance",
//     url: "/attendance",
//     icon: UserCheck,
//     roles: ["Admin", "Teacher", "Student"],
//     description: "Track attendance",
//     children: [
//       {
//         title: "Dashboard",
//         url: "/attendance",
//         icon: BarChart3,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Mark Attendance",
//         url: "/attendance/mark",
//         icon: UserCheck,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Monthly Calendar",
//         url: "/attendance/calendar",
//         icon: Calendar,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//       {
//         title: "Student Details",
//         url: "/attendance/student-detail",
//         icon: GraduationCap,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//       {
//         title: "Reports",
//         url: "/attendance/reports",
//         icon: BarChart3,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Settings",
//         url: "/attendance/settings",
//         icon: Settings,
//         roles: ["Admin"],
//       },
//     ],
//   },
//   {
//     title: "Examinations",
//     url: "/examinations",
//     icon: BookOpen,
//     roles: ["Admin", "Teacher", "Student"],
//     description: "Exam management",
//     children: [
//       {
//         title: "Dashboard",
//         url: "/examinations",
//         icon: BarChart3,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//       {
//         title: "Schedule",
//         url: "/examinations/schedule",
//         icon: Calendar,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//       {
//         title: "Marks Entry",
//         url: "/examinations/marks-entry",
//         icon: BookOpen,
//         roles: ["Admin", "Teacher"],
//       },
//       {
//         title: "Results",
//         url: "/examinations/results",
//         icon: BarChart3,
//         roles: ["Admin", "Teacher", "Student"],
//       },
//     ],
//   },
//   {
//     title: "Fee Management",
//     url: "/fees",
//     icon: DollarSign,
//     roles: ["Admin", "Accountant", "Student"],
//     description: "Manage fees",
//     children: [
//       {
//         title: "Dashboard",
//         url: "/fees",
//         icon: BarChart3,
//         roles: ["Admin", "Accountant"],
//       },
//       {
//         title: "Collection",
//         url: "/fees/collection",
//         icon: DollarSign,
//         roles: ["Admin", "Accountant"],
//       },
//       {
//         title: "Master Setup",
//         url: "/fees/master",
//         icon: Settings,
//         roles: ["Admin"],
//       },
//       {
//         title: "Structure Setup",
//         url: "/fees/structure",
//         icon: Settings,
//         roles: ["Admin"],
//       },
//       {
//         title: "Student Details",
//         url: "/fees/student-details",
//         icon: GraduationCap,
//         roles: ["Admin", "Accountant", "Student"],
//       },
//       {
//         title: "Defaulters",
//         url: "/fees/defaulters",
//         icon: Users,
//         roles: ["Admin", "Accountant"],
//       },
//       {
//         title: "Reports",
//         url: "/fees/reports",
//         icon: BarChart3,
//         roles: ["Admin", "Accountant"],
//       },
//     ],
//   },
//   {
//     title: "HR Management",
//     url: "/hr",
//     icon: Users,
//     roles: ["Admin", "HR"],
//     description: "Human resources",
//     children: [
//       {
//         title: "HR Dashboard",
//         url: "/hr",
//         icon: BarChart3,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Employees",
//         url: "/hr/employees",
//         icon: Users,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Attendance",
//         url: "/hr/attendance",
//         icon: UserCheck,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Leaves",
//         url: "/hr/leaves",
//         icon: Calendar,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Payroll",
//         url: "/hr/payroll",
//         icon: DollarSign,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Performance",
//         url: "/hr/performance",
//         icon: BarChart3,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Departments",
//         url: "/hr/departments",
//         icon: Users,
//         roles: ["Admin", "HR"],
//       },
//       {
//         title: "Substitution",
//         url: "/hr/substitution",
//         icon: UserCheck,
//         roles: ["Admin", "HR"],
//       },
//     ],
//   },
//   {
//     title: "User Management",
//     url: "/users",
//     icon: Users,
//     roles: ["Admin"],
//     description: "Manage users and permissions",
//     children: [
//       { title: "Dashboard", url: "/users", icon: BarChart3, roles: ["Admin"] },
//       { title: "All Users", url: "/users/list", icon: Users, roles: ["Admin"] },
//       { title: "Add User", url: "/users/add", icon: UserPlus, roles: ["Admin"] },
//       { title: "Roles", url: "/roles", icon: Shield, roles: ["Admin"] },
//       { title: "Permissions", url: "/permissions", icon: Key, roles: ["Admin"] },
//       {
//         title: "Permission Matrix",
//         url: "/permissions/matrix",
//         icon: Settings,
//         roles: ["Admin"],
//       },
//       { title: "Menu Access", url: "/menu-access", icon: Menu, roles: ["Admin"] },
//       { title: "Audit Trail", url: "/audit-trail", icon: Clock, roles: ["Admin"] },
//     ],
//   },
//   {
//     title: "Student Portal",
//     url: "/student-portal",
//     icon: GraduationCap,
//     roles: ["Student"],
//     description: "Student resources",
//   },
//   {
//     title: "Parent Portal",
//     url: "/parent",
//     icon: Home,
//     roles: ["Admin"],
//     description: "Parent communication",
//     children: [
//       {
//         title: "Dashboard",
//         url: "/parent",
//         icon: BarChart3,
//         roles: ["Admin"],
//       },
//       {
//         title: "Teacher Chat",
//         url: "/parent/chat",
//         icon: MessageSquare,
//         roles: ["Admin"],
//       },
//       {
//         title: "Leave Apply",
//         url: "/parent/leave-apply",
//         icon: Calendar,
//         roles: ["Admin"],
//       },
//     ],
//   },
//   {
//     title: "Transport",
//     url: "/transport",
//     icon: Bus,
//     roles: ["Admin"],
//     description: "Transport management",
//     children: [
//       { title: "Dashboard", url: "/transport", icon: BarChart3, roles: ["Admin"] },
//       { title: "Routes", url: "/transport/routes", icon: Route, roles: ["Admin"] },
//       { title: "Vehicles", url: "/transport/vehicles", icon: Bus, roles: ["Admin"] },
//       { title: "Drivers", url: "/transport/drivers", icon: Users, roles: ["Admin"] },
//       {
//         title: "Live Tracking",
//         url: "/transport/tracking",
//         icon: MapPin,
//         roles: ["Admin"],
//       },
//       { title: "Reports", url: "/transport/reports", icon: BarChart3, roles: ["Admin"] },
//     ],
//   },
//   {
//     title: "Hostel",
//     url: "/hostel",
//     icon: Building2,
//     roles: ["Admin"],
//     description: "Hostel management",
//     children: [
//       { title: "Dashboard", url: "/hostel", icon: BarChart3, roles: ["Admin"] },
//       {
//         title: "Room Allocation",
//         url: "/hostel/rooms",
//         icon: Building2,
//         roles: ["Admin"],
//       },
//       { title: "Mess Menu", url: "/hostel/mess", icon: Utensils, roles: ["Admin"] },
//       {
//         title: "Visitor Tracking",
//         url: "/hostel/visitors",
//         icon: UserCheck2,
//         roles: ["Admin"],
//       },
//       { title: "Reports", url: "/hostel/reports", icon: BarChart3, roles: ["Admin"] },
//     ],
//   },
//   {
//     title: "Notifications",
//     url: "/notifications",
//     icon: Bell,
//     roles: ["Admin", "Teacher", "Student", "HR", "Accountant"],
//     description: "View notifications",
//   },
//   {
//     title: "Settings",
//     url: "/settings",
//     icon: Settings,
//     roles: ["Admin"],
//     description: "System settings",
//   },
// ];
